/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate the latent weight trend and forecast it
         * @description Analyse a submitted series of weigh-ins.
         *
         *     Returns the filtered latent-weight trajectory with 95% intervals, the current estimate
         *     and weekly rate, and the 7-, 30- and 90-day forecasts with the band between them.
         */
        post: operations["analyse_api_analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the synthetic demo scenarios
         * @description List every available demo scenario. All of them are generated, none measured.
         */
        get: operations["demo_catalogue_api_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analyse a synthetic demo scenario
         * @description Generate the named scenario, ending just before now, and analyse it.
         *
         *     The response is the same shape as ``POST /api/analyse`` with the scenario's provenance
         *     added, so a client needs only one renderer.
         */
        get: operations["demo_analysis_api_demo__scenario__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse an uploaded CSV into observations ready for /api/analyse
         * @description Parse an uploaded CSV file into validated, normalised observations.
         *
         *     Does not analyse anything. Call ``POST /api/analyse`` next with the returned
         *     ``accepted`` list to get a trend and forecast -- the same call a manually entered
         *     series makes, since ``accepted`` is already shaped as ``ObservationIn`` (ADR-0010). No
         *     row count from this endpoint is logged; the parse report reaches the caller directly and
         *     nowhere else.
         */
        post: operations["ingest_csv_route_api_ingest_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Report that the service is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisMetaOut
         * @description Statements about what the numbers mean, so that a client need not assume.
         */
        AnalysisMetaOut: {
            /**
             * Filtered Not Smoothed
             * @description The trajectory is the online estimate: each point reflects only the data available at that instant, so it never changes retroactively (ADR-0005).
             * @default true
             */
            filtered_not_smoothed: boolean;
            /**
             * Interval Describes
             * @description Intervals describe the underlying weight, not what a scale would read. The latter is wider by the measurement variance and answers a different question.
             * @default latent_weight
             * @constant
             */
            interval_describes: "latent_weight";
            /**
             * Source
             * @description Where the observations came from. demo: generated by this API, synthetic by construction. submitted: provided by the caller; the server cannot know their provenance and makes no claim about it.
             * @enum {string}
             */
            source: "submitted" | "demo";
        };
        /**
         * AnalysisRequest
         * @description A series of weigh-ins to analyse.
         */
        AnalysisRequest: {
            /**
             * Forecast From
             * @description The value now measures horizons from the current instant, so a stale series carries the extra elapsed uncertainty. The value last_observation measures them from the final weigh-in.
             * @default now
             * @enum {string}
             */
            forecast_from: "now" | "last_observation";
            /**
             * Observations
             * @description Weigh-ins in any order; they are sorted chronologically on ingestion.
             */
            observations: components["schemas"]["ObservationIn"][];
        };
        /**
         * AnalysisResponse
         * @description Everything the analysis produces from a series of weigh-ins.
         */
        AnalysisResponse: {
            current: components["schemas"]["CurrentEstimateOut"];
            forecast: components["schemas"]["ForecastOut"];
            meta: components["schemas"]["AnalysisMetaOut"];
            /** N Obs */
            n_obs: number;
            /** Observations */
            observations: components["schemas"]["ObservationOut"][];
            params: components["schemas"]["ModelParamsOut"];
            /** Span Days */
            span_days: number;
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPointOut"][];
        };
        /**
         * CsvIngestResponse
         * @description The result of parsing one CSV upload: what to submit, and what to fix.
         *
         *     ``accepted`` is ready to pass straight into ``AnalysisRequest.observations``. Nothing
         *     here is analysed -- ``n_obs``, ``span_days``, a trend or a forecast only exist after
         *     calling ``POST /api/analyse`` with ``accepted``.
         */
        CsvIngestResponse: {
            /**
             * Accepted
             * @description Rows that parsed successfully, normalised to kilograms and UTC.
             */
            accepted: components["schemas"]["ObservationIn"][];
            /**
             * Accepted Count
             * @description Number of rows in accepted.
             */
            accepted_count: number;
            /**
             * Blank Rows Skipped
             * @description Fully empty rows: skipped, not rejected.
             */
            blank_rows_skipped: number;
            /**
             * Date Only Count
             * @description The subset of naive_timestamp_count that were date-only rows (no time of day), assigned 12:00 local time in assumed_timezone as a deterministic convention.
             */
            date_only_count: number;
            /**
             * Duplicate Count
             * @description Exact-duplicate observations (same resolved timestamp and canonical weight) beyond the first in each group -- three identical readings contribute 2, not 3 or 1. Duplicates are retained in accepted, not removed; this only counts them, the same way the underlying filter treats them as repeated measurements rather than a no-op.
             */
            duplicate_count: number;
            /**
             * Issues Truncated
             * @description True if more rows were rejected than the rejected list includes.
             */
            issues_truncated: boolean;
            /**
             * Naive Timestamp Count
             * @description Accepted rows whose timestamp carried no UTC offset and was therefore resolved using assumed_timezone. Includes date-only rows -- see date_only_count for that subset specifically.
             */
            naive_timestamp_count: number;
            /**
             * Rejected
             * @description Up to 500 rejected rows; see issues_truncated for the rest.
             */
            rejected: components["schemas"]["CsvRowIssue"][];
            /**
             * Rejected Count
             * @description Total rejected rows, regardless of truncation.
             */
            rejected_count: number;
        };
        /**
         * CsvRowIssue
         * @description One row that was not accepted, and why -- never what it contained.
         */
        CsvRowIssue: {
            /**
             * Line
             * @description 1-based physical line the record starts on. For a record spanning multiple physical lines (a quoted cell containing a newline), this is the starting line, not the line the record happens to end on.
             */
            line: number;
            /**
             * Message
             * @description Fixed explanation. Never contains a submitted value.
             */
            message: string;
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "missing_timestamp" | "missing_weight" | "unparseable_timestamp" | "ambiguous_local_time" | "nonexistent_local_time" | "non_numeric_weight" | "non_positive_weight" | "non_finite_weight" | "timestamp_out_of_range" | "invalid_unit" | "conflicting_unit" | "column_count_mismatch" | "invalid_row";
        };
        /**
         * CurrentEstimateOut
         * @description The estimate as of the last observation: weight, uncertainty and weekly rate.
         */
        CurrentEstimateOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** W Kg */
            w_kg: number;
            /** W Lower95 */
            w_lower95: number;
            /** W Sd */
            w_sd: number;
            /** W Upper95 */
            w_upper95: number;
            /** Weekly Rate Kg */
            weekly_rate_kg: number;
            /** Weekly Rate Sd Kg */
            weekly_rate_sd_kg: number;
        };
        /**
         * DemoAnalysisResponse
         * @description An analysis of a generated scenario: the standard response plus its provenance.
         */
        DemoAnalysisResponse: {
            current: components["schemas"]["CurrentEstimateOut"];
            forecast: components["schemas"]["ForecastOut"];
            meta: components["schemas"]["AnalysisMetaOut"];
            /** N Obs */
            n_obs: number;
            /** Observations */
            observations: components["schemas"]["ObservationOut"][];
            params: components["schemas"]["ModelParamsOut"];
            scenario: components["schemas"]["DemoScenarioOut"];
            /** Span Days */
            span_days: number;
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPointOut"][];
        };
        /**
         * DemoCatalogueResponse
         * @description The list of scenarios available to try.
         */
        DemoCatalogueResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["DemoScenarioOut"][];
            /**
             * Synthetic
             * @description Every scenario here is generated. None of it is measured health data.
             * @default true
             * @constant
             */
            synthetic: true;
        };
        /**
         * DemoScenarioOut
         * @description What a demo scenario is, and exactly what generated it.
         */
        DemoScenarioOut: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Label
             * @description Provenance label. Always identifies the data as synthetic.
             */
            label: string;
            /**
             * Parameters
             * @description The generator arguments, published so the series can be reproduced.
             */
            parameters: {
                [key: string]: number | string;
            };
            /** Seed */
            seed: number;
            /** Title */
            title: string;
        };
        /**
         * ErrorBody
         * @description The contents of an error response.
         */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable error identifier.
             */
            code: string;
            /**
             * Details
             * @description Field-level problems, present only for request-validation failures.
             */
            details?: components["schemas"]["ErrorDetail"][];
            /**
             * Message
             * @description Fixed human-readable explanation.
             */
            message: string;
        };
        /**
         * ErrorDetail
         * @description One field-level validation problem.
         */
        ErrorDetail: {
            /**
             * Code
             * @description Stable identifier for the kind of validation failure.
             */
            code: string;
            /**
             * Location
             * @description Dotted path to the offending field, using positions for list indices.
             */
            location: string;
            /**
             * Message
             * @description Fixed explanation. Never contains a submitted value.
             */
            message: string;
        };
        /**
         * ErrorResponse
         * @description The envelope returned for every non-2xx response.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ForecastOut
         * @description The forecast, and enough context to label it honestly.
         *
         *     Three quantities matter here and all three are published. ``origin_timestamp`` is what
         *     the horizons are measured from; ``last_observation_timestamp`` is the most recent real
         *     measurement; ``lead_days`` is the gap between them. A client that renders "30-day
         *     forecast" without knowing the lead cannot tell the user whether that means 30 days from
         *     their last weigh-in or 30 days from today (ADR-0005).
         */
        ForecastOut: {
            /** Horizons */
            horizons: components["schemas"]["ForecastPointOut"][];
            /** Includes Observation Noise */
            includes_observation_noise: boolean;
            /**
             * Last Observation Timestamp
             * Format: date-time
             */
            last_observation_timestamp: string;
            /** Lead Days */
            lead_days: number;
            /**
             * Origin Timestamp
             * Format: date-time
             */
            origin_timestamp: string;
            /** Path */
            path: components["schemas"]["ForecastPointOut"][];
        };
        /**
         * ForecastPointOut
         * @description The predictive distribution of latent weight at one horizon.
         */
        ForecastPointOut: {
            /** Horizon Days */
            horizon_days: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** W Kg */
            w_kg: number;
            /** W Lower95 */
            w_lower95: number;
            /** W Sd */
            w_sd: number;
            /** W Upper95 */
            w_upper95: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Confirmation that the service is running.
         *
         *     Deliberately contains no data, no timestamp and no dependency check: the point of a
         *     liveness endpoint is that it cannot fail for an interesting reason.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @description The API version.
             */
            version: string;
        };
        /**
         * ModelParamsOut
         * @description The model parameters used, echoed for transparency.
         *
         *     These are documented priors, not values fitted to this or any data. They are published
         *     so that a caller can see what produced the numbers, not so that they can be tuned.
         */
        ModelParamsOut: {
            /** Initial Weekly Rate Spread Kg Per Week */
            initial_weekly_rate_spread_kg_per_week: number;
            /** Sigma Accel */
            sigma_accel: number;
            /** Sigma Obs Kg */
            sigma_obs_kg: number;
            /** Sigma V0 */
            sigma_v0: number;
            /** Weekly Rate Drift Kg Per Week */
            weekly_rate_drift_kg_per_week: number;
        };
        /**
         * ObservationIn
         * @description One submitted weight measurement.
         */
        ObservationIn: {
            /**
             * Timestamp
             * Format: date-time
             * @description ISO-8601 instant of the weigh-in. Must carry a timezone offset, and must not be so late that a 90-day forecast from it is unrepresentable.
             */
            timestamp: string;
            /**
             * Unit
             * @description Unit of the weight field.
             * @default kg
             * @enum {string}
             */
            unit: "kg" | "lb";
            /**
             * Weight
             * @description The measured value, in the unit given by the unit field.
             */
            weight: number;
        };
        /**
         * ObservationOut
         * @description One normalised observation, in kilograms and UTC.
         */
        ObservationOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /**
         * TrajectoryPointOut
         * @description One point on the estimated latent-weight path.
         */
        TrajectoryPointOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** W Kg */
            w_kg: number;
            /** W Lower95 */
            w_lower95: number;
            /** W Sd */
            w_sd: number;
            /** W Upper95 */
            w_upper95: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyse_api_analyse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description The request was rejected. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    demo_catalogue_api_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoCatalogueResponse"];
                };
            };
        };
    };
    demo_analysis_api_demo__scenario__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoAnalysisResponse"];
                };
            };
            /** @description No such demo scenario. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_csv_route_api_ingest_csv_post: {
        parameters: {
            query: {
                /** @description IANA timezone (e.g. Europe/London) used to resolve timestamps with no UTC offset. Ignored for timestamps that already carry one. */
                assumed_timezone: string;
                /** @description Unit assumed for a weight column with no per-row or header-implied unit. */
                default_unit: "kg" | "lb";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvIngestResponse"];
                };
            };
            /** @description The file was too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request's Content-Type was not text/csv. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was rejected. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
